listen_addr: 0.0.0.0:5000
internal_endpoint_access_whitelist:
  - 127.0.0.1/8
  - 192.168.0.0/16
  - 10.0.0.0/8
  - 172.16.0.0/12
  - ::1/128
  - fc00::/7
connection_redis_sync:
  addr: redis://localhost:6379/0?client_name=wsgateway
stream_redis:
  addr: redis://localhost:6379/0?client_name=wsgatewaystream&pool_size=1000
max_message_size_kb: 1024
endpoints:
  - path: /connect
    set_tags:
      foo: bar
      other: tag
    stream_include_tags:
      - foo
      - group
    max_message_size_kb: 2048

  - path: /connect/v2
    set_tags:
      version: 2
    stream_include_tags:
      - version
      - group
prometheus:
  enabled: true
